---
- name: Check if ccoctl already exists
  ansible.builtin.stat:
    path: "{{ ccoctl_install_path }}"
  register: ccoctl_status

- name: Download and install ccoctl if not present
  become: true
  when: not ccoctl_status.stat.exists
  block:
    - name: Get installer version
      ansible.builtin.command:
        cmd: "{{ ocp_installer_bin_dir }} version"
      register: installer_version_output
      changed_when: false
      failed_when: false

    - name: Extract OpenShift version
      ansible.builtin.set_fact:
        ocp_version_full: "{{ (installer_version_output.stdout | split(' '))[0] }}"
      when: installer_version_output.stdout is defined

    - name: Define ccoctl download URL
      ansible.builtin.set_fact:
        ccoctl_url: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ openshift_version }}/ccoctl-linux.tar.gz"

    - name: Create /tmp directory
      ansible.builtin.file:
        path: "{{ working_dir }}"
        state: directory
        mode: '0755'

    - name: Download ccoctl
      unarchive:
        src: "{{ ccoctl_url }}"
        remote_src: yes
        dest: "{{ bin_dir }}"
        mode: '755'
        exclude:
          - README.md

    - name: Copy ccoctl
      file:
        path: "{{ bin_dir }}/{{ item }}"
        mode: "+x"
        state: touch
      loop:
        - ccoctl

- name: Verify ccoctl is now installed
  ansible.builtin.command:
    cmd: "{{ ccoctl_install_path }} help"
  register: ccoctl_version_output
  changed_when: false
...