---
- name: Install OpenShift 4.18 on AWS (IPI) using STS short-term credentials
  gather_facts: false
  hosts: localhost
  collections:
    - community.aws
    - amazon.aws

  tasks:
    - include_role:
        name: create_connected_aws_vpc

    - include_role:
        name: create_iam_roles
...